import { Attachment } from './Attachment';
import { MailIdentifier } from './MailIdentifier';
import { RxUser } from './RxUser';
import { MailLabel } from './MailLabel';
import { MailPriority } from './MailPriority';
import { MailBoxType } from './MailBoxType';
import { SendStatus } from './SendStatus';
import { AddressItem } from './AddressItem';

export const EntityMail = 'Mail';
export interface Mail {
  id?: number;
  subject?: string;
  from?: AddressItem;
  to?: AddressItem[];
  cc?: AddressItem[];
  bcc?: AddressItem[];
  date?: Date;
  messageId?: string;
  inReplyTo?: string;
  replyTo?: any;
  references?: any;
  html?: string;
  text?: string;
  priority?: MailPriority;
  inMailBox: MailBoxType;
  showAsOriginal?: boolean;
  fromAddress?: string;
  unRead?: boolean;
  answered?: boolean;
  deleted?: boolean;
  forwarded?: boolean;
  fromOldCustomer?: boolean;
  size?: number;
  inMailBoxBeforeDelete?: MailBoxType;
  scheduleSendDate?: Date;
  isSeparateSend?: boolean;
  sendStatus?: SendStatus;
  sendErrorMessage?: any[];
  fromConfigId?: number;
  createdAt?: Date;
  updatedAt?: Date;
  isPlainText?: boolean;
  headers?: any;
  receivedAddress?: string;
  toAddress?: string;
  htmlAsText?: string;
  owner?: RxUser;
  labels?: MailLabel[];
  attachments?: Attachment[];
  identifier?: MailIdentifier;
}
